config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admin/sessions' }, class_name: "Admin::Admin"
  devise_for :workers, controllers: { sessions: 'worker/sessions', passwords: 'worker/passwords' }, class_name: "Worker::Worker"

  root 'landing#landing_page'
  namespace :landing do
    post :track_shipment
  end

  namespace :admin do
    root 'dashboards#index'
    resources :dashboards, only: :index
    resource :profile, except: %i[create destroy]
    resources :shipments
    resources :workers
    resources :posts
  end

  namespace :worker do
    root 'dashboards#index'
    resources :dashboards, only: :index
    resource :profile, except: %i[new create destroy]
    resources :shipments do
      collection do
        post :state_shipment
      end
    end
    resources :payments, except: :show do
      collection do
        post :shipment_payment
      end
      member do
        delete :shipment_payment_delete
      end
    end
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def landing_page
    @top_sliders = Admin::Post.where(post_type: :top_slider, status: :active)
    @news = Admin::Post.where(post_type: :news, status: :active)
  end

  def track_shipment
    @shipment = Base::Shipment.find_by(code: params[:shipment_code])
  end
end

app/views/landing/_track_shipment.html.erb
<div class="form">
    <%= form_with url: landing_track_shipment_path do |f| %>
        <div class="form-group row">
            <div class="col-sm-10">
                <%= f.text_field :shipment_code, placeholder: 'SP0000', class: "form-control" %>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-4 col-sm-offset-2">
                <%= submit_tag "Search shipment", class: "btn btn-primary" %>
            </div>
        </div>
    <% end %>
</div>

app/views/landing/_track_shipment_info.html.erb
<div class="div">
    <% if @shipment %>
    <h3><%= t 'landing_shipment_track', id: @shipment.code, current_location: t("fields.shipment.#{@shipment.current_location}").html_safe %></h3>
    <% end %>
</div>

app/views/landing/track_shipment.js.erb
<% if @shipment %>
  $('#track_shipment_info').html("<%= j render 'track_shipment_info' %>")
<% else %>
  $('#track_shipment_info').html("<h3><%= t 'exuce_user_no_information_found_call_us' %></h3>")
<% end %>