config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admin/sessions' }, class_name: "Admin::Admin"
  devise_for :workers, controllers: { sessions: 'worker/sessions', passwords: 'worker/passwords' }, class_name: "Worker::Worker"

  root 'landing#landing_page'
  namespace :landing do
    post :track_shipment
  end

  namespace :admin do
    root 'dashboards#index'
    resources :dashboards, only: :index
    resource :profile, except: %i[create destroy]
    resources :shipments
    resources :workers
    resources :posts
  end

  namespace :worker do
    root 'dashboards#index'
    resources :dashboards, only: :index
    resource :profile, except: %i[new create destroy]
    resources :shipments do
      collection do
        post :state_shipment
      end
    end
    resources :payments, except: :show do
      collection do
        post :shipment_payment
      end
      member do
        delete :shipment_payment_delete
      end
    end
  end
end

app/models/admin/shipment.rb
module Admin

class Shipment < Base::Shipment
end

end

app/models/admin/worker.rb
module Admin

class Worker < Base::Worker
  before_create :set_password_encrypte
  before_update :set_password_encrypte

  attribute :password

  validates :name, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, presence: true, length: { maximum: 256 }
  validates_uniqueness_of :email
  validates :password, length: { minimum: 6, maximum: 20 }

  def set_password_encrypte
    require 'bcrypt'
    self.encrypted_password = BCrypt::Password.create(password)
  end

end

end

app/models/base/shipment.rb
module Base

class Shipment < ApplicationRecord

  has_many_attached :images

  enum delivery_type: [ :land, :air ]
  enum shipment_type: [ :normal, :express ]
  enum location_to: [ :ULN, :ISN ], _suffix: :to
  enum location_from: [ :ISN, :ULN ], _suffix: :from
  enum current_location: [ :in_korea_stock, :in_shipment, :in_bonded_storage, :waited_in_bonded_storage, :in_mongolia_stock, :delivered ]
  enum status: [ :registered, :delivering, :paid, :done ]

  belongs_to :created_worker, class_name: 'Base::Worker', foreign_key: :created_worker_id
  belongs_to :updated_worker, class_name: 'Base::Worker', foreign_key: :updated_worker_id

  after_initialize :preview_code
  after_create :set_code

  private

  def preview_code
    if self.new_record?
      sql = "select last_value from shipments_id_seq limit 1"
      record = ActiveRecord::Base.connection.execute(sql)
      self.code = format('SP%04d', (record.first['last_value'] + 1))
    end
  end

  def set_code
    self.update(:code => format('SP%04d', id))
  end
end

end

app/models/base/worker.rb
module Base

class Worker < ApplicationRecord
  has_one_attached :avatar

  enum is_manager: { employee: false, manager: true}
end

end

app/models/worker/payment.rb
module Worker

class Payment < ApplicationRecord
  belongs_to :shipment

  belongs_to :created_worker, class_name: 'Base::Worker', foreign_key: :created_worker_id
  belongs_to :updated_worker, class_name: 'Base::Worker', foreign_key: :updated_worker_id

  enum payment_type: [ :account, :cash ]

  validates :shipment_id, presence: true
  validates :amount_paid, presence: true

  def self.search(params)
    result = Payment.joins(:shipment)

    if params[:code].present?
      result = result.where("shipments.code like '%#{params[:code]}%'")
    end

    if params[:amount_paid].present?
      result = result.where("payments.amount_paid = #{params[:amount_paid]}")
    end

    if params[:start_date].present?
      result = result.where("payments.created_at >= '#{params[:start_date]}'")
    end

    if params[:end_date].present?
      result = result.where("payments.created_at <= '#{params[:end_date]}'")
    end

    if params[:payment_type].present?
      result = result.where("payments.payment_type = #{params[:payment_type]}")
    end

    result = result.order('payments.updated_at desc, payments.created_at desc')

    return result
  end
end

end

app/models/worker/shipment.rb
module Worker

class Shipment < Base::Shipment

  validates :weight, presence: true
  validates :phone, presence: true
  validates :status, presence: true

  def self.search(params)
    result = Shipment.select('*')

    if params[:code].present?
      result = result.where("code like '%#{params[:code]}%'")
    end

    if params[:price].present?
      result = result.where("price = #{params[:price]}")
    end

    if params[:start_date].present?
      result = result.where("created_at >= '#{params[:start_date]}'")
    end

    if params[:end_date].present?
      result = result.where("created_at <= '#{params[:end_date]}'")
    end

    if params[:status].present?
      result = result.where("status = #{params[:status]}")
    end

    result = result.order('created_at desc')

    return result
  end
end

end

app/models/worker/worker.rb
module Worker

class Worker < Base::Worker
  devise :database_authenticatable, :recoverable
end

end

app/controllers/admin/shipments_controller.rb
module Admin

class ShipmentsController < ApplicationController
  def index
    @shipments = Shipment.all.limit(100)
  end
end

end

app/controllers/admin/workers_controller.rb
module Admin

class WorkersController < ApplicationController
  before_action :target_worker, except: %i[index new create]

  def index
    @workers = Worker.all
  end

  def show
  end

  def new
    @worker = Worker.new
  end

  def create
    @worker = Worker.new(worker_params)
    if @worker.save
#       flash[:success] = t('global.save_success', subject: Admin::Account.model_name.human)
      redirect_to admin_workers_path(@worker)
    else
#       flash[:failure] = t('global.save_failure', subject: Admin::Account.model_name.human)
      render :new
    end
  end

  def edit
  end

  def update
    if @worker.update(worker_params)
      redirect_to admin_workers_path(@worker)
    else
      render :edit
    end
  end

  def destroy
    @worker.destroy
    redirect_to admin_workers_path
  end

  private

  def worker_params
    params.require(:admin_worker).permit(:name, :email, :password, :is_manager)
  end

  def target_worker
    @worker = Worker.find_by(id: params[:id])
  end
end

end

app/controllers/worker/application_controller.rb
module Worker

class ApplicationController < ApplicationController
  before_action :authenticate_worker!
  layout :monitoring_layout

  private

  def monitoring_layout
    'worker/layout'
  end
end

end

app/controllers/worker/dashboards_controller.rb
module Worker

class DashboardsController < ApplicationController

  def index
    p '________INDEXX___ADMIN_DASHBOARD___________'
    @dashboard = {shipments: nil}
    @dashboard[:shipments] = Shipment.all
  end
end

end

app/controllers/worker/passwords_controller.rb
module Worker

class PasswordsController < Devise::PasswordsController

  def new
  p '________________________RESET_PASSWORD_____________-',params
  p '________________________RESET_PASSWORD_____________-'
    super
  end

  def create
  p '_______CREATE____________RESET_PASSWORD_____________-',params
  p '_______CREATE_________________RESET_PASSWORD_____________-'
    super
  end

  def edit
    p '_______EDIT PASS_____________-',params
    p '_______EDIT PASS_____________-'
    super
  end

  # PUT /resource/password
  def update
  p '_______UPDATE PASS_____________-',params
      p '_______UPDATE PASS_____________-'
    super
  end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

end

app/controllers/worker/payments_controller.rb
module Worker

class PaymentsController < ApplicationController
  before_action :target_payment, except: %i[index new create]
  before_action :verify_role, except: %i[index new create edit shipment_payment]
  before_action :verify_role_shipment, only: :shipment_payment

  def index
    @payments = Payment.search(params).page(params[:page]).per(params[:limit])
  end

  def new
    @payment = Payment.new
  end

  def create
    create_params = payment_params.merge(created_worker_id: current_worker.id)
                                  .merge(updated_worker_id: current_worker.id)
    @payment = Payment.new(create_params)
    if @payment.save
      flash[:success] = t('global.save_success', subject: 'payment')
      redirect_to worker_payments_path
    else
      flash[:failure] = t('global.save_failure', subject: 'payment')
      render :new
    end
  end

  def edit
  end

  def update
    update_params = payment_params.merge(updated_worker_id: current_worker.id)
    if @payment.update(update_params)
      flash[:success] = t('global.save_success', subject: 'shipment')
      redirect_to worker_payments_path
    else
      flash[:failure] = t('global.save_failure', subject: 'shipment')
      render :edit
    end
  end

  def destroy
    @payment.destroy
    flash[:success] = t('global.save_success', subject: 'shipment')
    redirect_to worker_payments_path
  end

  def shipment_payment
    create_params = payment_params.merge(created_worker_id: current_worker.id)
                                  .merge(updated_worker_id: current_worker.id)
    @payment = Payment.new(create_params)
    if @payment.save
      flash[:failure] = nil
      flash[:success] = t('global.save_success', subject: 'payment')
    else
      flash[:success] = nil
      flash[:failure] = t('global.save_failure', subject: 'payment')
    end
    @payments = Payment.where(shipment_id: payment_params[:shipment_id]).order('created_at desc')
  end

  def shipment_payment_delete
    @payment.destroy
    flash[:success] = t('global.save_success', subject: 'payment')
    @payments = Payment.where(shipment_id: @payment.shipment_id).order('created_at desc')
  end

  private

  def target_payment
    @payment = Payment.find_by(id: params[:id])
  end

  def verify_role
    if !current_worker.manager? && @payment.created_worker_id != current_worker.id
      flash[:failure] = t('global.save_failure', subject: "only manager can modify other user's data")
      redirect_to worker_payments_path
    end
  end

  def verify_role_shipment
    shipment = Shipment.find_by(id: payment_params[:shipment_id])
    if !current_worker.manager? && shipment.created_worker_id != current_worker.id
      flash[:failure] = t('global.save_failure', subject: "only manager can modify other user's data")
      redirect_to worker_payments_path
    end
  end

  def payment_params
      params.require(:worker_payment).permit(:shipment_id,
                                             :amount_paid,
                                             :payment_type,
                                             :note)
    end

end

end

app/controllers/worker/profiles_controller.rb
module Worker

class ProfilesController < ApplicationController
  before_action :target_worker

  def show
  p '_____________________signded worker show____________________-'
  end

  def edit
  p '_____________________signded worker edit____________________-'
  end

  def update
  p '_____________________signded worker upudate____________________-'
    if @profile.update(profile_params)
      redirect_to worker_profile_path(@profile)
    else
      render :edit
    end
  end

  private

  def target_worker
    @profile = Worker.find_by(id: current_worker.id)
  end

  def profile_params
    params.require(:worker_worker).permit(:name, :email, :delivery_date, :avatar)
  end
end

end

app/controllers/worker/sessions_controller.rb
class Worker::SessionsController < Devise::SessionsController
end

app/controllers/worker/shipments_controller.rb
module Worker

class ShipmentsController < ApplicationController
  before_action :target_shipment, except: %i[index new create]
  before_action :verify_role, only: %i[update destroy]

  def index
    @shipments = Shipment.search(params).page(params[:page]).per(params[:limit])
  end

  def show
    @payments = Payment.where(shipment_id: @shipment.id).order('created_at desc')
  end

  def new
    @shipment = Shipment.new
  end

  def create
    create_params = shipment_params.merge(status_history: params[:worker_shipment][:status])
                                   .merge(created_worker_id: current_worker.id)
                                   .merge(updated_worker_id: current_worker.id)
    @shipment = Shipment.new(create_params)
    if @shipment.save
      flash[:success] = t('global.save_success', subject: 'shipment')
      redirect_to worker_shipments_path
    else
      flash[:failure] = t('global.save_failure', subject: 'shipment')
      render :new
    end
  end

  def edit
  end

  def update
    update_params = shipment_params.except(:status)
                                   .merge(updated_worker_id: current_worker.id)
    if @shipment.update(update_params)
      flash[:success] = t('global.save_success', subject: 'shipment')
      redirect_to worker_shipments_path
    else
      flash[:failure] = t('global.save_failure', subject: 'shipment')
      render :edit
    end
  end

  def destroy
    @shipment.destroy
    flash[:success] = t('global.save_success', subject: 'shipment')
    redirect_to worker_shipments_path
  end

  def state_shipment
    if @shipment.update({status: params[:status], status_history: "#{@shipment.status_history}, #{params[:status]}"})
      flash[:failure] = nil
      flash[:success] = t('global.save_success', subject: 'shipment')
    else
      flash[:success] = nil
      flash[:failure] = t('global.save_failure', subject: 'shipment')
    end
  end

  private

  def target_shipment
    @shipment = Shipment.find_by(id: params[:id])
  end

  def verify_role
    if !current_worker.manager? && @shipment.created_worker_id != current_worker.id
      flash[:failure] = t('global.save_failure', subject: "only manager can modify other user's data")
      redirect_to worker_shipments_path
    end
  end

  def shipment_params
    params.require(:worker_shipment).permit(:weight,
                                            :delivery_type,
                                            :shipment_type,
                                            :location_to,
                                            :location_from,
                                            :price,
                                            :status,
                                            :current_location,
                                            :shipment_definition,
                                            :shipment_object_description,
                                            :about_payment,
                                            :note,
                                            :delivery_date,
                                            :phone,
                                            :email,
                                            :customer_name,
                                            :customer_phone,
                                            :customer_address,
                                            :recipient_name,
                                            :recipient_phone,
                                            :recipient_address,
                                            images: [])
  end
end

end

app/views/worker/shipments/_shipment_payment.html.erb
<h2 class="font-bold m-b-xs">
    Payment detail <small>total: </small><%= @payments.count %>
</h2>
<table class="table table-hover">
    <thead>
        <tr>
            <th>Data</th>
            <th>Paid amount</th>
            <th>Type</th>
            <th>Note</th>
        </tr>
    </thead>
    <tbody>
        <% @payments.each do |payment| %>
            <tr>
                <td>
                    <span class="pie" style="display: none;"><%= payment.amount_paid %></span>
                    <svg class="peity" height="16" width="16">
                        <path d="M 8 8 L 8 0 A 8 8 0 0 1 14.933563796318165 11.990700825968545 Z" fill="#1ab394"></path>
                        <path d="M 8 8 L 14.933563796318165 11.990700825968545 A 8 8 0 1 1 7.999999999999998 0 Z" fill="#d7d7d7"></path>
                    </svg>
                </td>
                <% if payment.amount_paid > 0 %>
                    <td class="text-navy">
                        <i class="fa fa-level-up"></i> <%= payment.amount_paid %>
                    </td>
                <% else %>
                    <td class="text-warning">
                        <i class="fa fa-level-down"></i> <%= payment.amount_paid %>
                    </td>
                <% end %>
                <td><%= payment.payment_type %></td>
                <td><%= payment.note %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/worker/shipments/_table.html.erb
<div class="table-responsive">
<table class="table table-striped" data-paging="false">
    <thead>
        <tr>
            <th id="shipment_ids_all"><%= check_box_tag 'shipment_ids_all' %></th>
            <th>Code</th>
            <th>Shipment Type</th>
            <th>Delivery type</th>
            <th>Weight</th>
            <th>Status</th>
            <th>Price</th>
            <th>Location</th>
            <th>Ship object</th>
            <th>Phone</th>
            <th>Created at</th>
            <th>Current location</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <% @shipments.each do |shipment| %>
        <tr>
            <td id="shipment_ids"><%= check_box_tag 'shipment_ids[]', shipment.id %></td>
            <td><a class="fa fa-expand" href="<%= worker_shipment_path(shipment) %>"><%= shipment.code %></a></td>
            <td><%= shipment.shipment_type %></td>
            <td><%= shipment.delivery_type %></td>
            <td><%= shipment.weight %></td>
            <td>
                <% if shipment.status == 'done' %>
                <span class="label label-success"><%= shipment.status %></span>
                <% elsif shipment.status == 'paid' %>
                <span class="label label-primary"><%= shipment.status %></span>
                <% elsif shipment.status == 'delivering' %>
                <span class="label label-info"><%= shipment.status %></span>
                <% else %>
                <span class="label label-warning"><%= shipment.status %></span>
                <% end %>
            </td>
            <td><%= shipment.price %></td>
            <td><%= shipment.location_to %></td>
            <td><%= shipment.shipment_object_description %></td>
            <td><%= shipment.phone %></td>
            <td>
                <small><%= shipment.created_at.strftime("%m/%d/%y") %></small>
                <small><%= shipment.created_worker.name %></small>
            </td>
            <td><%= t("fields.shipment.#{shipment.current_location}") %></td>
            <td class="text-right">
                <div class="btn-group">
                    <a href="<%= worker_shipment_path(shipment) %>" class="btn btn-white btn-sm"><i class="fa fa-folder"></i> Detail </a>
                    <a href="<%= edit_worker_shipment_path(shipment) %>" class="btn btn-white btn-sm"><i class="fa fa-pencil"></i> Edit </a>
                    <%= link_to 'Delete', worker_shipment_path(shipment), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-white btn btn-xs btn-danger btn-outline" %>
                </div>
            </td>
        </tr>
        <% end%>
    </tbody>
    <tfoot>
        <td colspan="16">
            <ul class="float-right" id="paginator">
                <%= paginate @shipments, remote: true %>
            </ul>
            <ul>
                count: <%= @shipments.total_count %>
                limit: <%= @shipments.limit_value %>
            </ul>
        </td>
    </tfoot>
</table>
</div>

<script>
    $(document).ready(function() {
        // $('.footable').footable({ paginate: false });
    });
</script>

app/views/worker/shipments/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-4">
    <h2>Shipment</h2>
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="<%= worker_shipments_path %>">Home</a>
      </li>
      <li class="breadcrumb-item active">
        <strong>Shipment edit</strong>
      </li>
    </ol>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInUp">
  <%= render 'form' %>
</div>

app/views/worker/shipments/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-4">
    <h2>Shipment</h2>
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="<%= worker_shipments_path %>">Home</a>
      </li>
      <li class="breadcrumb-item active">
        <strong>Shipment list</strong>
      </li>
    </ol>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight ecommerce">
  <div class="ibox-content m-b-sm border-bottom">
    <%= form_with url: worker_shipments_path, method: :get do |f| %>
      <div class="row">
        <div class="col-sm-2">
          <div class="form-group">
            <label class="col-form-label" for="code">Code</label>
            <%= f.text_field :code, placeholder: 'Code', class: 'form-control' %>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="form-group">
            <label class="col-form-label" for="price">Price</label>
            <%= f.number_field :price, placeholder: 'Price', class: 'form-control' %>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="form-group">
            <label class="col-form-label">Delivery date range</label>
            <div class="input-daterange input-group" id="datepicker">
              <%= f.date_field :start_date, placeholder: 'Delivery date', class: 'form-control' %>
              <span class="input-group-addon">~</span>
              <%= f.date_field :end_date, placeholder: 'Delivery date', class: 'form-control' %>
            </div>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="form-group">
            <label class="col-form-label" for="status">Status</label>
            <select name="status" id="status" class="form-control">
              <option selected></option>
              <option value="0">Registered</option>
              <option value="1">delivering</option>
              <option value="2">paid</option>
              <option value="3">done</option>
            </select>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="form-group">
            <label class="col-form-label" for="status">.</label>
            <span class="input-group-append">
              <%= f.submit "Search", class: 'btn btn-block btn-outline btn-success' %>
            </span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <a href="<%= new_worker_shipment_path %>" class="btn btn-outline btn-primary">Create new shipment</a>

          <div class="html5buttons">
            <div class="dt-buttons btn-group flex-wrap">
              <button class="btn btn-white btn-sm buttons-copy buttons-html5" tabindex="0" aria-controls="DataTables_Table_0" type="button"><span>Copy</span></button>
              <button class="btn btn-white btn-sm buttons-csv buttons-html5" tabindex="0" aria-controls="DataTables_Table_0" type="button"><span>CSV</span></button>
              <button class="btn btn-white btn-sm buttons-excel buttons-html5" tabindex="0" aria-controls="DataTables_Table_0" type="button"><span>Excel</span></button>
              <button class="btn btn-white btn-sm buttons-pdf buttons-html5" tabindex="0" aria-controls="DataTables_Table_0" type="button"><span>PDF</span></button>
              <button class="btn btn-white btn-sm buttons-print" tabindex="0" aria-controls="DataTables_Table_0" type="button"><span>Print</span></button>
            </div>
          </div>
        </div>
        <div class="ibox-content">
          <%= render :partial => 'table' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/worker/shipments/index.js.erb
$('table').html("<%= j render 'table' %>")
<!--$("#paginator").html("<%= escape_javascript(paginate(@shipments, remote: true)) %>")-->
$('.footable').footable({ paginate: false });

app/views/worker/shipments/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Shipment</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="<%= worker_shipments_path %>">Home</a>
            </li>
            <li class="breadcrumb-item active">
                <strong>Shipment show</strong>
            </li>
        </ol>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInUp">
    <div class="ibox-content m-b-sm border-bottom">
        <div class="row">
            <div class="col-6">
                <div id="shipment_payment_form">
                    <%= form_tag shipment_payment_worker_payments_path(@shipment), remote: true do %>
                    <%= hidden_field_tag "worker_payment[shipment_id]", @shipment.id, class: 'form-control' %>
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group row">
                                <div class="col-sm-10">
                                    <%= number_field_tag "worker_payment[amount_paid]", '', placeholder: 'amount paid', class: 'form-control' %>
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-10">
                                    <%= select_tag "worker_payment[payment_type]", options_for_select(['account', 'cash']), class: 'form-control' %>
                                </div>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group row">
                                <div class="col-sm-10">
                                    <%= text_field_tag "worker_payment[note]", '', placeholder: 'Note', class: 'form-control' %>
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <%= submit_tag "Create payment", class: "btn btn-primary" %>
                                </div>
                            </div>
                        </div>
                    </div>
                    <% end %>
                </div>
            </div>
            <div class="col-6">
                <div id="state_shipment_form">
                    <%= form_with url: state_shipment_worker_shipments_path do |f| %>
                    <%= f.hidden_field :id, value: @shipment.id, class: "form-control" %>
                    <div class="form-group row">
                        <div class="col-sm-10">
                            <%= f.select(:status, ['registered', 'delivering', 'paid', 'done'], {}, { :class => 'form-control' }) %>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-4 col-sm-offset-2">
                            <%= submit_tag "Change status", class: "btn btn-primary" %>
                        </div>
                    </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox product-detail">
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-md-5">
                            <div id="carouselExampleInterval" class="carousel slide" data-ride="carousel">
                                <% if @shipment.images.attached? %>
                                    <div class="carousel-inner">
                                        <% i = 0 %>
                                        <% @shipment.images.each do |image| %>
                                            <% if i == 0 %>
                                                <% active = "active" %>
                                            <% else %>
                                                <% active = "" %>
                                            <% end %>
                                            <div class="carousel-item <%= active %>">
                                                <%= image_tag(url_for(image), style: 'height:100%;width:auto;') %>
                                            </div>
                                            <% i = i + 1 %>
                                        <% end %>
                                    </div>
                                <% end %>
                                <a class="slick-prev slick-arrow" href="#carouselExampleInterval" role="button" data-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"><<<</span>
                                    <span class="sr-only">Previous</span>
                                </a>
                                <a class="slick-next slick-arrow" href="#carouselExampleInterval" role="button" data-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true">>>></span>
                                    <span class="sr-only">Next</span>
                                </a>
                                <% if @shipment.images.attached? %>
                                    <% i = 0 %>
                                    <ol class="carousel-indicators">
                                        <% @shipment.images.each do |image| %>
                                            <% if i == 0 %>
                                            <% active = "active" %>
                                            <% end %>
                                            <li data-target="#carouselExampleIndicators" data-slide-to="<%= i %>" class="<%= active %>"</li>
                                        <% i = i + 1 %>
                                        <% end %>
                                    </ol>
                                <% end %>
                            </div>
                        </div>
                        <div class="col-md-7">
                            <div id="state_shipment">
                                <%= render :partial => 'state_shipment' %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div id="shipment_payments">
                <%= render :partial => 'worker/payments/shipment_payment' %>
            </div>
        </div>
    </div>
</div>

app/views/worker/shipments/state_shipment.js.erb
$('#flash_containner').html("<%= j render 'layouts/shared/flash' %>")

<% if @shipment.errors.any? %>
    <% @shipment.errors.messages.each do |key, value| %>
        $('#state_shipment_form #<%= key %>').addClass('error')
        $('#state_shipment_form #<%= key %>').parent().append('<label class="error"><%= value.join(', ') %></label>')
    <% end %>
<% else %>
    $("#state_shipment_form .form-control").removeClass('error')
    $('#state_shipment_form label.error').remove();
    $('#state_shipment').html("<%= j render 'state_shipment' %>")
<% end %>