config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admin/sessions' }, class_name: "Admin::Admin"
  devise_for :workers, controllers: { sessions: 'worker/sessions', passwords: 'worker/passwords' }, class_name: "Worker::Worker"

  root 'landing#landing_page'
  namespace :landing do
    post :track_shipment
  end

  namespace :admin do
    root 'dashboards#index'
    resources :dashboards, only: :index
    resource :profile, except: %i[create destroy]
    resources :shipments
    resources :workers
    resources :posts
  end

  namespace :worker do
    root 'dashboards#index'
    resources :dashboards, only: :index
    resource :profile, except: %i[new create destroy]
    resources :shipments do
      collection do
        post :state_shipment
      end
    end
    resources :payments, except: :show do
      collection do
        post :shipment_payment
      end
      member do
        delete :shipment_payment_delete
      end
    end
  end
end

app/views/layouts/admin/_footer.html.erb
<div class="float-right">
    10GB of <strong>250GB</strong> Free.
</div>
<div>
    <strong>Copyright</strong> Example Company © 2014-2019
</div>

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
        <form role="search" class="navbar-form-custom" action="#">
            <div class="form-group">
                <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
            </div>
        </form>
    </div>
    <ul class="nav navbar-top-links navbar-right">
        <li style="padding: 20px">
            <span class="m-r-sm text-muted welcome-message">Welcome to INSPINIA+ Admin Theme.</span>
        </li>
        <li class="dropdown">
            <a class="btn" href="<%= admin_root_path(locale: :mn) %>"><%= image_tag "flags/16/Mongolia.png" %> MN</a>
        </li>
        <li class="dropdown">
            <a class="btn" href="<%= admin_root_path(locale: :kr) %>"><%= image_tag "flags/16/North-Korea.png" %> KR</a>
        </li>
        <li>
            <%= link_to destroy_admin_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>Log out
            <% end %>
        </li>
        <li>
            <a class="right-sidebar-toggle">
                <i class="fa fa-tasks"></i>
            </a>
        </li>
    </ul>
</nav>

app/views/layouts/admin/_navigation.html.erb
<div class="sidebar-collapse">
    <ul class="nav metismenu" id="side-menu">
        <li class="nav-header">
            <div class="dropdown profile-element">
                <%= image_tag 'admin.png', alt: "image", class: "rounded-circle" %>
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <span class="block m-t-xs font-bold">David Williams</span>
                    <span class="text-muted text-xs block">Art Director <b class="caret"></b></span>
                </a>
                <ul class="dropdown-menu animated fadeInRight m-t-xs">
                    <li><a class="dropdown-item" href="<%= admin_profile_path %>">Profile</a></li>
                    <li><a class="dropdown-item" href="contacts.html">Contacts</a></li>
                    <li class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="login.html">Logout</a></li>
                </ul>
            </div>
            <div class="logo-element">
                IN+
            </div>
        </li>
        <li>
            <a href="#"><i class="fa fa-th-large"></i> <span class="nav-label">Dashboards</span> <span class="fa arrow"></span></a>
            <ul class="nav nav-second-level collapse">
                <li><a href="<%= admin_dashboards_path %>">Dashboard v.1</a></li>
                <li><a href="<%= admin_dashboards_path %>">Dashboard v.2</a></li>
            </ul>
        </li>
        <li>
            <a href="<%= admin_dashboards_path %>"><i class="fa fa-pie-chart"></i> <span class="nav-label">Dashboard</span></a>
        </li>
        <li>
            <a href="<%= admin_profile_path %>"><i class="fa fa-user"></i> <span class="nav-label">Profile</span></a>
        </li>
        <li>
            <a href="<%= admin_shipments_path %>" aria-expanded="false"><i class="fa fa-shopping-cart"></i><span class="nav-label">Shipments</span></a>
        </li>
        <li>
            <a href="<%= admin_workers_path %>" aria-expanded="false"><i class="fa fa-group"></i><span class="nav-label">Workers</span></a>
        </li>
        <li>
            <a href="<%= admin_posts_path %>" aria-expanded="false"><i class="fa fa-hacker-news"></i><span class="nav-label">Posts</span></a>
        </li>
    </ul>
</div>

app/views/layouts/admin/layout.html.erb
<head>
  <title>Cargo Monitoring</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body class="pace-done">
<div id="wrapper">
  <nav class="navbar-default navbar-static-side" role="navigation">
    <%= render "layouts/admin/navigation" %>
  </nav>

  <div id="page-wrapper" class="gray-bg dashbard-1">
    <div class="row border-bottom">
      <%= render "layouts/admin/header" %>
    </div>
    <div id="flash_containner">
      <%= render 'layouts/shared/flash' %>
    </div>

    <%= yield %>

    <div class="footer">
      <%= render "layouts/admin/footer" %>
    </div>
  </div>
</body>
</body>
</html>