config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admin/sessions' }, class_name: "Admin::Admin"
  devise_for :workers, controllers: { sessions: 'worker/sessions', passwords: 'worker/passwords' }, class_name: "Worker::Worker"

  root 'landing#landing_page'
  namespace :landing do
    post :track_shipment
  end

  namespace :admin do
    root 'dashboards#index'
    resources :dashboards, only: :index
    resource :profile, except: %i[create destroy]
    resources :shipments
    resources :workers
    resources :posts
  end

  namespace :worker do
    root 'dashboards#index'
    resources :dashboards, only: :index
    resource :profile, except: %i[new create destroy]
    resources :shipments do
      collection do
        post :state_shipment
      end
    end
    resources :payments, except: :show do
      collection do
        post :shipment_payment
      end
      member do
        delete :shipment_payment_delete
      end
    end
  end
end

app/models/admin/worker.rb
module Admin

class Worker < Base::Worker
  before_create :set_password_encrypte
  before_update :set_password_encrypte

  attribute :password

  validates :name, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, presence: true, length: { maximum: 256 }
  validates_uniqueness_of :email
  validates :password, length: { minimum: 6, maximum: 20 }

  def set_password_encrypte
    require 'bcrypt'
    self.encrypted_password = BCrypt::Password.create(password)
  end

end

end

app/models/base/worker.rb
module Base

class Worker < ApplicationRecord
  has_one_attached :avatar

  enum is_manager: { employee: false, manager: true}
end

end

app/models/worker/payment.rb
module Worker

class Payment < ApplicationRecord
  belongs_to :shipment

  belongs_to :created_worker, class_name: 'Base::Worker', foreign_key: :created_worker_id
  belongs_to :updated_worker, class_name: 'Base::Worker', foreign_key: :updated_worker_id

  enum payment_type: [ :account, :cash ]

  validates :shipment_id, presence: true
  validates :amount_paid, presence: true

  def self.search(params)
    result = Payment.joins(:shipment)

    if params[:code].present?
      result = result.where("shipments.code like '%#{params[:code]}%'")
    end

    if params[:amount_paid].present?
      result = result.where("payments.amount_paid = #{params[:amount_paid]}")
    end

    if params[:start_date].present?
      result = result.where("payments.created_at >= '#{params[:start_date]}'")
    end

    if params[:end_date].present?
      result = result.where("payments.created_at <= '#{params[:end_date]}'")
    end

    if params[:payment_type].present?
      result = result.where("payments.payment_type = #{params[:payment_type]}")
    end

    result = result.order('payments.updated_at desc, payments.created_at desc')

    return result
  end
end

end

app/models/worker/shipment.rb
module Worker

class Shipment < Base::Shipment

  validates :weight, presence: true
  validates :phone, presence: true
  validates :status, presence: true

  def self.search(params)
    result = Shipment.select('*')

    if params[:code].present?
      result = result.where("code like '%#{params[:code]}%'")
    end

    if params[:price].present?
      result = result.where("price = #{params[:price]}")
    end

    if params[:start_date].present?
      result = result.where("created_at >= '#{params[:start_date]}'")
    end

    if params[:end_date].present?
      result = result.where("created_at <= '#{params[:end_date]}'")
    end

    if params[:status].present?
      result = result.where("status = #{params[:status]}")
    end

    result = result.order('created_at desc')

    return result
  end
end

end

app/models/worker/worker.rb
module Worker

class Worker < Base::Worker
  devise :database_authenticatable, :recoverable
end

end

app/controllers/admin/workers_controller.rb
module Admin

class WorkersController < ApplicationController
  before_action :target_worker, except: %i[index new create]

  def index
    @workers = Worker.all
  end

  def show
  end

  def new
    @worker = Worker.new
  end

  def create
    @worker = Worker.new(worker_params)
    if @worker.save
#       flash[:success] = t('global.save_success', subject: Admin::Account.model_name.human)
      redirect_to admin_workers_path(@worker)
    else
#       flash[:failure] = t('global.save_failure', subject: Admin::Account.model_name.human)
      render :new
    end
  end

  def edit
  end

  def update
    if @worker.update(worker_params)
      redirect_to admin_workers_path(@worker)
    else
      render :edit
    end
  end

  def destroy
    @worker.destroy
    redirect_to admin_workers_path
  end

  private

  def worker_params
    params.require(:admin_worker).permit(:name, :email, :password, :is_manager)
  end

  def target_worker
    @worker = Worker.find_by(id: params[:id])
  end
end

end

app/controllers/worker/application_controller.rb
module Worker

class ApplicationController < ApplicationController
  before_action :authenticate_worker!
  layout :monitoring_layout

  private

  def monitoring_layout
    'worker/layout'
  end
end

end

app/controllers/worker/dashboards_controller.rb
module Worker

class DashboardsController < ApplicationController

  def index
    p '________INDEXX___ADMIN_DASHBOARD___________'
    @dashboard = {shipments: nil}
    @dashboard[:shipments] = Shipment.all
  end
end

end

app/controllers/worker/passwords_controller.rb
module Worker

class PasswordsController < Devise::PasswordsController

  def new
  p '________________________RESET_PASSWORD_____________-',params
  p '________________________RESET_PASSWORD_____________-'
    super
  end

  def create
  p '_______CREATE____________RESET_PASSWORD_____________-',params
  p '_______CREATE_________________RESET_PASSWORD_____________-'
    super
  end

  def edit
    p '_______EDIT PASS_____________-',params
    p '_______EDIT PASS_____________-'
    super
  end

  # PUT /resource/password
  def update
  p '_______UPDATE PASS_____________-',params
      p '_______UPDATE PASS_____________-'
    super
  end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

end

app/controllers/worker/payments_controller.rb
module Worker

class PaymentsController < ApplicationController
  before_action :target_payment, except: %i[index new create]
  before_action :verify_role, except: %i[index new create edit shipment_payment]
  before_action :verify_role_shipment, only: :shipment_payment

  def index
    @payments = Payment.search(params).page(params[:page]).per(params[:limit])
  end

  def new
    @payment = Payment.new
  end

  def create
    create_params = payment_params.merge(created_worker_id: current_worker.id)
                                  .merge(updated_worker_id: current_worker.id)
    @payment = Payment.new(create_params)
    if @payment.save
      flash[:success] = t('global.save_success', subject: 'payment')
      redirect_to worker_payments_path
    else
      flash[:failure] = t('global.save_failure', subject: 'payment')
      render :new
    end
  end

  def edit
  end

  def update
    update_params = payment_params.merge(updated_worker_id: current_worker.id)
    if @payment.update(update_params)
      flash[:success] = t('global.save_success', subject: 'shipment')
      redirect_to worker_payments_path
    else
      flash[:failure] = t('global.save_failure', subject: 'shipment')
      render :edit
    end
  end

  def destroy
    @payment.destroy
    flash[:success] = t('global.save_success', subject: 'shipment')
    redirect_to worker_payments_path
  end

  def shipment_payment
    create_params = payment_params.merge(created_worker_id: current_worker.id)
                                  .merge(updated_worker_id: current_worker.id)
    @payment = Payment.new(create_params)
    if @payment.save
      flash[:failure] = nil
      flash[:success] = t('global.save_success', subject: 'payment')
    else
      flash[:success] = nil
      flash[:failure] = t('global.save_failure', subject: 'payment')
    end
    @payments = Payment.where(shipment_id: payment_params[:shipment_id]).order('created_at desc')
  end

  def shipment_payment_delete
    @payment.destroy
    flash[:success] = t('global.save_success', subject: 'payment')
    @payments = Payment.where(shipment_id: @payment.shipment_id).order('created_at desc')
  end

  private

  def target_payment
    @payment = Payment.find_by(id: params[:id])
  end

  def verify_role
    if !current_worker.manager? && @payment.created_worker_id != current_worker.id
      flash[:failure] = t('global.save_failure', subject: "only manager can modify other user's data")
      redirect_to worker_payments_path
    end
  end

  def verify_role_shipment
    shipment = Shipment.find_by(id: payment_params[:shipment_id])
    if !current_worker.manager? && shipment.created_worker_id != current_worker.id
      flash[:failure] = t('global.save_failure', subject: "only manager can modify other user's data")
      redirect_to worker_payments_path
    end
  end

  def payment_params
      params.require(:worker_payment).permit(:shipment_id,
                                             :amount_paid,
                                             :payment_type,
                                             :note)
    end

end

end

app/controllers/worker/profiles_controller.rb
module Worker

class ProfilesController < ApplicationController
  before_action :target_worker

  def show
  p '_____________________signded worker show____________________-'
  end

  def edit
  p '_____________________signded worker edit____________________-'
  end

  def update
  p '_____________________signded worker upudate____________________-'
    if @profile.update(profile_params)
      redirect_to worker_profile_path(@profile)
    else
      render :edit
    end
  end

  private

  def target_worker
    @profile = Worker.find_by(id: current_worker.id)
  end

  def profile_params
    params.require(:worker_worker).permit(:name, :email, :delivery_date, :avatar)
  end
end

end

app/controllers/worker/sessions_controller.rb
class Worker::SessionsController < Devise::SessionsController
end

app/controllers/worker/shipments_controller.rb
module Worker

class ShipmentsController < ApplicationController
  before_action :target_shipment, except: %i[index new create]
  before_action :verify_role, only: %i[update destroy]

  def index
    @shipments = Shipment.search(params).page(params[:page]).per(params[:limit])
  end

  def show
    @payments = Payment.where(shipment_id: @shipment.id).order('created_at desc')
  end

  def new
    @shipment = Shipment.new
  end

  def create
    create_params = shipment_params.merge(status_history: params[:worker_shipment][:status])
                                   .merge(created_worker_id: current_worker.id)
                                   .merge(updated_worker_id: current_worker.id)
    @shipment = Shipment.new(create_params)
    if @shipment.save
      flash[:success] = t('global.save_success', subject: 'shipment')
      redirect_to worker_shipments_path
    else
      flash[:failure] = t('global.save_failure', subject: 'shipment')
      render :new
    end
  end

  def edit
  end

  def update
    update_params = shipment_params.except(:status)
                                   .merge(updated_worker_id: current_worker.id)
    if @shipment.update(update_params)
      flash[:success] = t('global.save_success', subject: 'shipment')
      redirect_to worker_shipments_path
    else
      flash[:failure] = t('global.save_failure', subject: 'shipment')
      render :edit
    end
  end

  def destroy
    @shipment.destroy
    flash[:success] = t('global.save_success', subject: 'shipment')
    redirect_to worker_shipments_path
  end

  def state_shipment
    if @shipment.update({status: params[:status], status_history: "#{@shipment.status_history}, #{params[:status]}"})
      flash[:failure] = nil
      flash[:success] = t('global.save_success', subject: 'shipment')
    else
      flash[:success] = nil
      flash[:failure] = t('global.save_failure', subject: 'shipment')
    end
  end

  private

  def target_shipment
    @shipment = Shipment.find_by(id: params[:id])
  end

  def verify_role
    if !current_worker.manager? && @shipment.created_worker_id != current_worker.id
      flash[:failure] = t('global.save_failure', subject: "only manager can modify other user's data")
      redirect_to worker_shipments_path
    end
  end

  def shipment_params
    params.require(:worker_shipment).permit(:weight,
                                            :delivery_type,
                                            :shipment_type,
                                            :location_to,
                                            :location_from,
                                            :price,
                                            :status,
                                            :current_location,
                                            :shipment_definition,
                                            :shipment_object_description,
                                            :about_payment,
                                            :note,
                                            :delivery_date,
                                            :phone,
                                            :email,
                                            :customer_name,
                                            :customer_phone,
                                            :customer_address,
                                            :recipient_name,
                                            :recipient_phone,
                                            :recipient_address,
                                            images: [])
  end
end

end

app/views/layouts/worker/_footer.html.erb
<div class="float-right">
    10GB of <strong>250GB</strong> Free.
</div>
<div>
    <strong>Copyright</strong> Example Company © 2014-2019
</div>

app/views/layouts/worker/_header.html.erb
<nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
        <form role="search" class="navbar-form-custom" action="#">
            <div class="form-group">
                <input type="text" placeholder="Search for something..." class="form-control">
            </div>
        </form>
    </div>
    <ul class="nav navbar-top-links navbar-right">
        <li style="padding: 20px">
            <span class="m-r-sm text-muted welcome-message">Welcome to INSPINIA+ Admin Theme.</span>
        </li>
        <li class="dropdown">
            <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                <i class="fa fa-envelope"></i>  <span class="label label-warning">16</span>
            </a>
            <ul class="dropdown-menu dropdown-messages dropdown-menu-right">
                <li class="dropdown-divider"></li>
                <li>
                    <div class="text-center link-block">
                        <a href="mailbox.html" class="dropdown-item">
                            <i class="fa fa-envelope"></i> <strong>Read All Messages</strong>
                        </a>
                    </div>
                </li>
            </ul>
        </li>
        <li class="dropdown">
            <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                <i class="fa fa-bell"></i>  <span class="label label-primary">8</span>
            </a>
            <ul class="dropdown-menu dropdown-alerts">
                <li>
                    <a href="mailbox.html" class="dropdown-item">
                        <div>
                            <i class="fa fa-envelope fa-fw"></i> You have 16 messages
                            <span class="float-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="dropdown-divider"></li>
                <li>
                    <a href="profile.html" class="dropdown-item">
                        <div>
                            <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                            <span class="float-right text-muted small">12 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="dropdown-divider"></li>
                <li>
                    <a href="grid_options.html" class="dropdown-item">
                        <div>
                            <i class="fa fa-upload fa-fw"></i> Server Rebooted
                            <span class="float-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="dropdown-divider"></li>
                <li>
                    <div class="text-center link-block">
                        <a href="notifications.html" class="dropdown-item">
                            <strong>See All Alerts</strong>
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </div>
                </li>
            </ul>
        </li>
        <li>
            <%= link_to destroy_worker_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>Log out
            <% end %>
        </li>
        <li>
            <a class="right-sidebar-toggle">
                <i class="fa fa-tasks"></i>
            </a>
        </li>
    </ul>
</nav>

app/views/layouts/worker/_navigation.html.erb
<div class="sidebar-collapse">
    <ul class="nav metismenu" id="side-menu">
        <li class="nav-header">
            <div class="dropdown profile-element">
                <% if current_worker.avatar.attached? %>
                    <%= image_tag(url_for(current_worker.avatar), size: "128", alt: 'image', class: "rounded-circle") %>
                <% else %>
                    <%= image_tag 'profile_empty.jpg', size: "128", alt: "image", class: "rounded-circle" %>
                <% end %>
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <span class="block m-t-xs font-bold"><%= current_worker.name %></span>
                    <span class="text-muted text-xs block">Art Director <b class="caret"></b></span>
                </a>
                <ul class="dropdown-menu animated fadeInRight m-t-xs">
                    <li><a class="dropdown-item" href="<%= worker_profile_path %>">Profile</a></li>
                    <li><a class="dropdown-item" href="<%= worker_dashboards_path %>">Contacts</a></li>
                    <li class="dropdown-divider"></li>
                    <li>
                        <a class="dropdown-item" href="login.html">
                            <%= link_to destroy_worker_session_path, method: :delete do %>
                            <i class="fa fa-sign-out"></i>Log out
                            <% end %>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="logo-element">
                IN+
            </div>
        </li>
        <li class="<%= 'active' if @dashboard %>">
            <a href="<%= worker_dashboards_path %>"><i class="fa fa-pie-chart"></i> <span class="nav-label">Dashboard</span></a>
        </li>
        <li class="<%= 'active' if @profile %>">
            <a href="<%= worker_profile_path %>"><i class="fa fa-user"></i> <span class="nav-label">Profile</span></a>
        </li>
        <li class="<%= 'active' if @shipments %>">
            <a href="<%= worker_shipments_path %>" aria-expanded="false"><i class="fa fa-shopping-cart"></i><span class="nav-label">Shipments</span></a>
        </li>
        <li class="<%= 'active' if @payments %>">
            <a href="<%= worker_payments_path %>" aria-expanded="false"><i class="fa fa-dollar"></i><span class="nav-label">Paymens</span></a>
        </li>
    </ul>
</div>

app/views/layouts/worker/layout.html.erb
<head>
  <title>Cargo Monitoring</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body class="pace-done">
<div id="wrapper">
  <nav class="navbar-default navbar-static-side" role="navigation">
    <%= render "layouts/worker/navigation" %>
  </nav>

  <div id="page-wrapper" class="gray-bg dashbard-1">
    <div class="row border-bottom">
      <%= render "layouts/worker/header" %>
    </div>
    <div id="flash_containner">
      <%= render 'layouts/shared/flash' %>
    </div>

    <%= yield %>

    <div class="footer">
      <%= render "layouts/worker/footer" %>
    </div>
  </div>
</body>
</body>
</html>